"""initial admin schema

Revision ID: bfef7aabd7b4
Revises: 
Create Date: 2026-05-22 01:17:22.593230
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bfef7aabd7b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_config',
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('scoring_threshold', sa.Integer(), nullable=False),
    sa.Column('topics_per_run', sa.Integer(), nullable=False),
    sa.Column('banned_phrases', sa.Text(), nullable=False),
    sa.Column('voice_profile', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('prompt_type', sa.String(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('test_results', sa.Text(), nullable=True),
    sa.CheckConstraint("prompt_type IN ('writer_polish', 'writer_draft', 'topic_picker', 'image_prompt')", name='ck_prompts_prompt_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index('idx_active_prompt', ['brand_id', 'prompt_type'], unique=True, sqlite_where=sa.text('is_active = 1'))
        batch_op.create_index(batch_op.f('ix_prompts_brand_id'), ['brand_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('source_ids', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index('ix_runs_started_at', ['started_at'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('primary_category', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('paywall', sa.Boolean(), nullable=False),
    sa.Column('polling_minutes', sa.Integer(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('custom_parser', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('rss', 'web', 'telegram')", name='ck_sources_source_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_brand_active', ['brand_id', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_brand_id'), ['brand_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filter_reason', sa.Text(), nullable=True),
    sa.Column('draft_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('passed', 'filtered_banned', 'filtered_dup', 'filtered_score', 'failed')", name='ck_topics_status'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'topic_id', name='uq_topics_run_topic')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topics_run_id'))

    op.drop_table('topics')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_brand_id'))
        batch_op.drop_index('ix_sources_brand_active')

    op.drop_table('sources')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_started_at')
        batch_op.drop_index(batch_op.f('ix_runs_brand_id'))

    op.drop_table('runs')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_brand_id'))
        batch_op.drop_index('idx_active_prompt', sqlite_where=sa.text('is_active = 1'))

    op.drop_table('prompts')
    op.drop_table('pipeline_config')
    # ### end Alembic commands ###
